### ISSUE TITLE
tooltips for magic_factory gui

### ISSUE THREAD

**Issue by carsen-stringer** [napari/magicgui#172]
Thanks so much for this awesome software, it's really helpful! 

I was wondering if there could be some way to specify the tooltip for a given widget in a @magic_factory decorated function? @sofroniewn suggested that maybe it could be pulled from the docstring?

**Comment by tlambert03** [comment]
Yep, sorry that hasn't made it into the documentation yet.

### default behavior
By default (i.e. if you do nothing at all) tooltips will be added to the widgets using the function docstring (note I'm showing `@magicgui` here, but `@magic_factory` takes all the same parameters and behaves the same way):

```python
from magicgui import magicgui

@magicgui
def f(x=1, y='hi'):
    """My function.

    Parameters
    ----------
    x : int
        This is the x parameter...
    y : str
        And this is y!
    """
    ...

f.show(run=True)
```

(cursor is over the "y" field, but it doesn't show up in screenshot)

<img width="204" alt="a" src="https://user-images.githubusercontent.com/1609449/109543746-ad873580-7a94-11eb-8583-9903d5206967.png">

note: docstrings must be valid [numpy](https://numpydoc.readthedocs.io/en/latest/format.html), [google](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) or [sphinx](https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html) docstring format.  (prefer numpy if you don't otherwise have a preference)


### override or directly provide content
you can override the content of tooltip for each parameter (or avoid using docstrings altogether), using the `tooltip` key in one of the [parameter-specific options (https://napari.org/magicgui/usage/configuration.html#parameter-specific-options).

```python
@magicgui(y={"tooltip": 'this is my tooltip'})
def f(x=1, y='hi'):
	...

f.show(run=True)
```
<img width="200" alt="b" src="https://user-images.githubusercontent.com/1609449/109544524-aad91000-7a95-11eb-94c3-f47648dc1d96.png">

### outside of `magicgui`

and a general reminder `magicgui` and `magic_factory` are just convenient ways to create magicgui widgets from function parameters.  All of the [direct widget constructors](https://napari.org/magicgui/usage/direct_api.html) take a `tooltip` argument:

```python
from magicgui import widgets

edit = widgets.LineEdit(value='hello', tooltip='just a tooltip')
edit.show(run=True)
```

<img width="205" alt="c" src="https://user-images.githubusercontent.com/1609449/109544996-3eaadc00-7a96-11eb-8133-f7107a20b5b3.png">

**Comment by carsen-stringer** [comment]
Thanks for the fast response, that's awesome! Thanks also for the direct widget creation info, I may end up using that instead

**Comment by tlambert03** [comment]
you're welcome!

> Thanks also for the direct widget creation info, I may end up using that instead

yeah I'd like to see more people use that.  I think use of `@magicgui` and `@magic_factory` should be restricted to cases where you need input to a specific function.  Note that you can also compose sub-widgets, some of which may have been created with magicgui, and others directly.  Feel free to reach out for more guidance on that.
