### ISSUE TITLE
Default values are ignored by `magic_factory`

### ISSUE THREAD

**Issue by brisvag** [napari/magicgui#242]
**Describe the bug**

```python
from magicgui import magic_factory
@magic_factory
def factory(arg=None):
    ...
factory()()
```
This fails with
```
TypeError: missing a required argument: 'arg' in call to 'factory(arg)'.
To avoid this error, you can bind a value or callback to the parameter:

    factory.arg.bind(value)

Or use the 'bind' option in the magicgui decorator:

    @magicgui(arg={'bind': value})
    def factory(arg): ...
```

Indeed, this can be circumvented by adding `arg={'bind': None}` to the `magic_factory` call, but this is different from the bahviour of `@magicgui`.

**Comment by sofroniewn** [comment]
Not sure if bug i'm seeing is same issue as this, or i need to make a new issue, but if i do something like

```python
@magic_factory(call_button="run",
              spacing={'min': 10, 'max':10_000, 'step': 10, 'label': 'spacing (um)'},
)
def simulation(
               spacing: float=500,
               ) -> 'napari.types.LayerDataTuple':
    """Run a single simulation.
    """
    .....
```
when i add the widget i see `99.99` in the combobox instead of `500` as it looks like the min/ max values havn't gotten applied yet

for a real world example see https://github.com/sofroniewn/waver/pull/5/files# and 

<img width="1416" alt="Screen Shot 2021-07-10 at 12 12 41 PM" src="https://user-images.githubusercontent.com/6531703/125174159-28b1d400-e178-11eb-8d61-350de01032ef.png">

Note all `99.99` when the default value exceeds 100

**Comment by tlambert03** [comment]
different, will take a look.

**Comment by tlambert03** [comment]
hmm, I just tried this and it worked...

<img width="319" alt="Untitled" src="https://user-images.githubusercontent.com/1609449/125174319-9539cc80-e192-11eb-9630-49384f11eff0.png">

i believe that was an issue a while ago... what version are you using?

**Comment by sofroniewn** [comment]
> i believe that was an issue a while ago... what version are you using?

I was on `magicgui==0.2.6`, just upgraded to `magicgui-0.2.9` and works great now!!!!

My bad, sorry!! Will try and remember to upgrade next time.

**Comment by tlambert03** [comment]
ancient history!! :)
