### ISSUE TITLE
Removal of docks: are widgets singletons?

### ISSUE THREAD

**Issue by stefanv** [napari/magicgui#28]
I am writing an app that requires switching between two widgets, depending on the value of a checkbox.

Here's a snippet that I thought would do the trick:

```python
with napari.gui_qt():
    gui_state = {
        'latest': None
    }

    @magicgui(call_button='Recreate dock')
    def horizontal_widget(horizontal: bool = True, label: str = 'Horizontal'):
        """Adds, subtracts, multiplies, or divides two image layers of similar shape."""
        if not horizontal:
            viewer.window.remove_dock_widget(gui_state['latest'])
            vertical = vertical_widget.Gui()
            gui_state['latest'] = viewer.window.add_dock_widget(vertical)

        print("Fired: horizontal", horizontal)

    @magicgui(call_button='Recreate dock')
    def vertical_widget(horizontal: bool = False, label: str = 'Vertical'):
        """Adds, subtracts, multiplies, or divides two image layers of similar shape."""
        if horizontal:
            viewer.window.remove_dock_widget(gui_state['latest'])
            horizontal = horizontal_widget.Gui()
            gui_state['latest'] = viewer.window.add_dock_widget(horizontal)

        print("Fired: vertical", horizontal)

    viewer = napari.Viewer()
    viewer.add_image(image)
    gui_state['latest'] = viewer.window.add_dock_widget(horizontal_widget.Gui())
```

However, it looks like the Gui instances may be singletons, since I see the following segfault:

```
WARNING: Traceback (most recent call last):
  File "/home/stefan/envs/py38/lib/python3.8/site-packages/magicgui/core.py", line 199, in <lambda>
    self.call_button.clicked.connect(lambda checked: self.__call__())
  File "/home/stefan/envs/py38/lib/python3.8/site-packages/magicgui/core.py", line 527, in __call__
    self.called.emit(value)
RuntimeError: wrapped C/C++ object of type MagicGui has been deleted
```

I also noticed a discrepancy in the docs:

```
    def add_dock_widget(
...
        Parameters
        ----------
        widget : QWidget
            `widget` will be added as QDockWidget's main widget.
```

```
    def remove_dock_widget(self, widget):
        """Removes specified dock widget.

        Parameters
        ----------
            widget : QWidget | str
                If widget == 'all', all docked widgets will be removed.
        """
```

So, it looks like `add_dock_widget` and `remove_dock_widget` can take the same object as input.  But, instead, `add_dock_widget` manufactures a new widget that has to be provided as input to `remove_dock_widget`.  Perhaps it is worth clarifying in the docstring exactly which object should be used.

Sorry if I filed this in the wrong place: it seems to straddle Napari and magicgui.

Side question: I would love for this to trigger on clicking the checkbox, but looks like currently a button is needed to fire an action?  I couldn't find anything in the docs about "instant" updates.

Versions: napari (master), magicgui (master)

**Comment by tlambert03** [comment]
also curious, how do other python qt apps look on your system like Spyder or something

**Comment by tlambert03** [comment]
this is a very interesting case. No they're not singletons, but I think this is more of a magicgui issue.  Where I'm trying to be too clever by hooking up events to callbacks, and in this case, because the when the call button is clicked, the widget is actually removing the last reference to itself, which will trigger the Qt deleteLater cleanup, and so when some callback is called, it's gone.  I tried to figure it out quickly but couldn't, so will have to come back to this probably next week when I have more time.

This is actually not dissimilar to one of my "ultimate" hopes for magicgui, which would be to do something like have a dropdown that lets you pick any method from one of the scikit-image modules, which, when changed, renders the appropriate widget for that method and modifies the current napari image.  That wasn't going to actually delete the dock_widget itself, but it would be creating/destroying nested widgets... so it's conceivable this will be an issue there too.

> Side question: I would love for this to trigger on clicking the checkbox, but looks like currently a button is needed to fire an action? I couldn't find anything in the docs about "instant" updates.

there's a poorly documented parameter to the decorator called "auto_call"
```python
    @magicgui(auto_call=True)
    def vertical_widget(checked=False, label='Vertical'):
        print(f"The {label} box is {'not ' if checked else ''}checked")

    widget = vertical_widget.Gui(show=True)
```
It's mentioned in this example, but not documented elsewhere...
https://magicgui.readthedocs.io/en/latest/examples/napari_parameter_sweep/#the-magic-part


> Perhaps it is worth clarifying in the docstring exactly which object should be used.

definitely agree.

**Comment by tlambert03** [comment]
Hey @stefanv.  Finally getting back to this after a complete rewrite (#43).  I'm realizing now that this error might have been a Qt idiosyncrasy all along.  With the current master branch of magicgui, the following code works (note the addition of the `setParent(None)` calls prior to swapping the dock widget):

```python
import napari
from magicgui import magicgui

with napari.gui_qt():
    gui_state = {"latest": None}

    @magicgui(call_button="Recreate dock")
    def horizontal_widget(horizontal: bool = True, label: str = "Horizontal"):
        if not horizontal:
            viewer.window.remove_dock_widget(gui_state["latest"])
            horizontal_widget.native.setParent(None)  # !!!
            gui_state["latest"] = viewer.window.add_dock_widget(vertical_widget)

        print("Fired: horizontal", horizontal)

    @magicgui(call_button="Recreate dock")
    def vertical_widget(horizontal: bool = False, label: str = "Vertical"):
        if horizontal:
            viewer.window.remove_dock_widget(gui_state["latest"])
            vertical_widget.native.setParent(None)  # !!!
            gui_state["latest"] = viewer.window.add_dock_widget(horizontal_widget)

        print("Fired: vertical", horizontal)

    viewer = napari.Viewer()
    gui_state["latest"] = viewer.window.add_dock_widget(horizontal_widget)
```

without the `setParent(None)` calls you still get the `wrapped C/C++ object has been deleted` error.  
What I think is happening is that when you call `viewer.window.add_dock_widget`, it creates a  [DockWidget](https://doc.qt.io/archives/qt-4.8/qdockwidget.html) and makes it the parent of the "magicgui" widget (e.g. `horizontal_widget.native`).  So even though `horizontal_widget` still has a reference in the local, when we swap the values for `gui_state["latest"]` the other _dock widget_ loses its last reference and gets deleted.  By default, a deleted QWidget destroys all of its children.  So that's why orphaning the `horizontal_widget.native` widget prevents it from getting deleted and lets us go back and forth.

hope you haven't long since moved on and that this may still be useful for you! :joy:
I'll leave this open for a bit, let me know if you have any thoughts.
