### ISSUE TITLE
Mixing native Qt and magicgui widgets

### ISSUE THREAD

**Issue by aeisenbarth** [napari/magicgui#314]
## ❓ Questions and Help

I have a Napari dock in which I want to include several magicgui widgets (`Combobox[ImageData]`) and a complex existing native Qt widget for visualization. For the dock, I insert these into a container:

- If I use a magicgui `Container`, I get an error that the native widget cannot be wrapped in a _LabeledWidget ("… has no attribute _explicitly_hidden").
- If I use a native Qt container (e.g. QWidget with QVBoxLayout), the magicgui Combobox is deactivated and not populated with layers.

1. Is there a way to properly add native Qt widgets to a magicgui Container?
2. Is there a way to wrap a native Qt widget into something that turns it into a magicgui widget?
3. If not, since the set with magicgui widgets will always be smaller than the space of possible Qt widgets, would this make a good feature request?

[X] I have searched the [documentation](https://napari.org/magicgui)

**Comment by tlambert03** [comment]
hmm... the main tricky thing here is maintaining the "magic" napari behavior with annotated parameters

> Is there a way to properly add native Qt widgets to a magicgui Container?

there's no officially supported way to do this yet.  As you've found, it's only really designed to go the other way (using `widget.native`).  Since we don't want to close the door on magicgui being "backend agnostic" ... this will likely not happen soon.  but it's something to think about.

> Is there a way to wrap a native Qt widget into something that turns it into a magicgui widget?

not really, a magicgui widget really _contains_ the backend widget (rather than inherits from it)... 

> If not, since the set with magicgui widgets will always be smaller than the space of possible Qt widgets, would this make a good feature request?

you mean the request to wrap the Qt widget in a magicgui widget?  perhapppps... but it's not immediately clear to me how we'll define "success" in implementing this feature.  That is, what behaviors are we looking to preserve in doing this?  (It's probably going to be easier to add a QtWidget to a Container)

if you could perhaps provide a minimal example (you can use a stub `QWidget` in place of your complex existing Qt widget) of the widget layout, it might be helpful?
Is it basically just  this?

```
Container
   - mgui_widget_combobox: Layer
   - custom_qt_widget
   - ...
   - 
```

**Comment by aeisenbarth** [comment]
Thanks for the reply!
It was not obvious to me that a container would have a lot of magic behavior. I had assumed (if at all) then magicgui Container and Qt containers would be interchangeable. But since magicgui is a wrapper instead of inheriting, magicgui widgets cannot be added to Qt containers, but the other way around is maybe not impossible.

I think my layout can be described in reduced form as:

    dock: magicgui.widgets.Container
      - myfile_path: FileEdit
      - layer: Combobox[ImageData]
      - visualization: QtWidget
    
    def update():
        data = load_file(myfile_path)
        visualization.update(data.dataframe)
        layer.set_data(data.image)

    file_path.changed.connect(update)

Since I am doing the wiring myself (connecting to events), my use case does not need any magicgui behaviors between the Qt widget and its parent container.

I was able to achieve this layout by writing everything in native Qt widgets. The motivation of instead using magicgui would be:

- more user-friendly API (less code, a single line per widget)
- provides composite widgets (`FileEdit`) which are missing from Qt
- automatically binds widgets to Napari types (`ImageData`), which is much more complicated to replicate with native Qt widgets
