### ISSUE TITLE
Disabling readouts in Sliders not working?

### ISSUE THREAD

**Issue by jni** [napari/magicgui#328]
**Describe the bug**

```python
@magicgui(slider={'widget_type': 'Slider', 'label': ' ', 'readout': False})
def f(slider: int):
    pass

f.show()
```

I'd expect the above code to not display a readout widget of the current slider value, but it does.

Additionally, the readout config parameter is not documented in the docstring.

**Expected behavior**

I'd expect the above code to show me a slider with no readout widget.

**Environment (please complete the following information):**
 - OS: Linux
 - backend: PyQt5 5.15.4
 - magicgui version 0.3.3

**Comment by jni** [comment]
I had a brief browse through the code and it seems like the readout value isn't used at all during the creation of the native widget, but events are hooked up correctly so that using `f.slider.readout = False` will disable the readout. (You can even do this inside the function, but it needs a first call to take effect.)

@tlambert03 I realised don't actually know how native widgets are created from the mgui widget! :grimacing: Is that sequence of events explained somewhere?

**Comment by tlambert03** [comment]
fixing now,  it's a bug, but easily fixed by moving `self.readout = readout` to after `super().__init__`

> @tlambert03 I realised don't actually know how native widgets are created from the mgui widget! 😬 Is that sequence of events explained somewhere?

not in the end-user facing docs.  But it boils down to this:

- every widget is a subclass of magicgui.widgets.Widget
- The instantiation of the backend widget happens [here](https://github.com/napari/magicgui/blob/c06a82d6eea0a63a2aefa8d2784d927a518ca82c/magicgui/widgets/_bases/widget.py#L91)
- `widget_type` is provided to the `__init__` (it's a composition pattern) and it must be a any class that implements one of the widget protocols [here](https://github.com/napari/magicgui/blob/main/magicgui/widgets/_protocols.py)
- in the majority of cases, widgets are created by the [`create_widget`](https://github.com/napari/magicgui/blob/c06a82d6eea0a63a2aefa8d2784d927a518ca82c/magicgui/widgets/_bases/create_widget.py#L15) factory function, which does the job of calling `magicgui.type_map.get_widget_class` to determine what the widget_type is supposed to be, and calling the constructor.
- lastly, it's good to be aware of the [`backend_widget` decorator](https://github.com/napari/magicgui/blob/c06a82d6eea0a63a2aefa8d2784d927a518ca82c/magicgui/widgets/_concrete.py#L128), which injects a little bit of logic into the `__init__` [right here](https://github.com/napari/magicgui/blob/c06a82d6eea0a63a2aefa8d2784d927a518ca82c/magicgui/widgets/_concrete.py#L158-L164), to get the current backend, and find the implementation for the widget of the corresponding name:
https://github.com/napari/magicgui/blob/c06a82d6eea0a63a2aefa8d2784d927a518ca82c/magicgui/widgets/_concrete.py#L158-L164

**Comment by tlambert03** [comment]
another thing I'll point out:
the `Slider`-with-spinbox implementation here is one of the few "composite" widgets.  so it was tricker than the others... which makes mucking about in the backend a little more confusing.  This predates the superqt labeled sliders, which might be a better option now (though relying on that would mean that every backend would have to re-implement it)
