### ISSUE TITLE
Overwriting the widget_type of a a widget parameter

### ISSUE THREAD

**Issue by SebastienTs** [napari/magicgui#351]
I am able to modify the value of a magicgui widget parameter programatically with: **widget.param.value = val** and this also works for other properties (visible, label, ...), but I cannot overwrite the widget_type. Is there a way to do this programatically?

Also, widget.param.step seems to have no effect (I would have expected it to set the steps of for instance a slider).

**Comment by tlambert03** [comment]
you cannot change an existing widget instance into another type of widget instance.  you would need to pop the subwidget from the container, create a new widget and insert it.

```
container.pop(optional_position_of_subwidget)
new_widget = widgets.PushButton()  # for example
container.append(new_widget)
```

If you're using the `magicgui` decorator, this is essentially as if you had a changing function signature, so you might be better off using the [direct widget API](https://napari.org/magicgui/usage/direct_api.html) instead.

> Also, widget.param.step seems to have no effect (I would have expected it to set the steps of for instance a slider).

this is due to weird behavior in QSlider itself actually.  I agree, it's confusing behavior (we could try to "fix" qt's bug on our end ... but it's not a magicgui bug per se)
