### ISSUE TITLE
QTimeEdit widgets

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/magicgui#78]
Hey @tlambert03 

first of all: Happy New Year! 🥳 

I just programmed a magicgui-annotated function that has a `time` parameter (hh:mm:ss).  When starting up the GUI, I receive this warning:
```
UserWarning: Unable to find the appropriate widget for function "_clearcontrol_loader", arg "time", type "<class 'datetime.time'>". Falling back to LiteralEvalEdit widget.
  warnings.warn(
```
When entering a time then in the fallback QLineEdit field, this error shows up:
```
ERROR:root:Unhandled exception:
Traceback (most recent call last):
  File "C:\Users\rober\miniconda3\envs\clustering\lib\site-packages\magicgui\core.py", line 526, in __call__
    _kwargs = self.current_kwargs
  File "C:\Users\rober\miniconda3\envs\clustering\lib\site-packages\magicgui\core.py", line 500, in current_kwargs
    return {param: getattr(self, param) for param in self.param_names}
  File "C:\Users\rober\miniconda3\envs\clustering\lib\site-packages\magicgui\core.py", line 500, in <dictcomp>
    return {param: getattr(self, param) for param in self.param_names}
  File "C:\Users\rober\miniconda3\envs\clustering\lib\site-packages\magicgui\core.py", line 96, in __get__
    return api.getter_setter_onchange(widget).getter()
  File "C:\Users\rober\miniconda3\envs\clustering\lib\site-packages\magicgui\_qt\widgets\eval_lineedit.py", line 12, in text
    return literal_eval(super().text())
  File "C:\Users\rober\miniconda3\envs\clustering\lib\ast.py", line 59, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "C:\Users\rober\miniconda3\envs\clustering\lib\ast.py", line 47, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    1:00:00
     ^
SyntaxError: invalid syntax
```

My use case is quite specific: I'd like to [select a defined timepoints from a larger dataset for loading](https://github.com/haesleinhuepf/beetlesafari/commit/e496b630d64b01f9242ce761c86a74f3a7374ff9#diff-cfd3e44eed68b98b7063b5ffad6c7fc027592f1e47bf74eeccac66f3f4d392dfR10) and we image over multiple days with variable temporal resolution. 

Nevertheless, I think supporting [QTimeEdit](https://doc.qt.io/qt-5/qtimeedit.html) as widget type would be cool.

Let me know if I can help making this happen.

No hurry btw. I do have a functional workaround for now.

Cheers,
Robert

**Comment by tlambert03** [comment]
Hey @haesleinhuepf!  That should definitely be included and will be easy to do.

In the meantime, there _is_ a [DateTimeEdit widget](https://napari.org/magicgui/_autosummary/magicgui.widgets.DateTimeEdit.html?highlight=date%20time#magicgui.widgets.DateTimeEdit) if you annotate using `datetime.datetime` instead of `datetime.time` (and deal with the annoyance of having the date in their as well)

**Comment by tlambert03** [comment]
Oh also: if you annotate as `str` or use `{'widget_type': 'LineEdit'}` (instead of the literal eval variant, then it will allow you to input "HH:mm:ss" without a syntax error

**Comment by haesleinhuepf** [comment]
> In the meantime, there _is_ a [DateTimeEdit widget](https://napari.org/magicgui/_autosummary/magicgui.widgets.DateTimeEdit.html?highlight=date%20time#magicgui.widgets.DateTimeEdit) if you annotate using `datetime.datetime` instead of `datetime.time` (and deal with the annoyance of having the date in their as well)

This hint is fantastic. I can annotate my `timepoint` field like this:
```
@magicgui(timepoint={'displayFormat':'hh:mm:ss'})
```

... and get exactly the user interface I was looking for:
![image](https://user-images.githubusercontent.com/12660498/103439927-9917ef80-4c41-11eb-8e95-bfa5007926fb.png)

Big thanks!

**Comment by tlambert03** [comment]
wait a minute ... are you using magicgui 0.1.6?  the ability to pass Qt-specific attribute names like that is gone in 0.2.0, so it won't be there if you update.  The principle going forward is to fully separate the backend from the front-end.  It doesn't mean that we can't add back features like that (which I admit was very flexible!), but it will preferably be with a magicgui API rather than directly using the Qt API (unless we decide it was just too useful to omit).  and, as mentioned above, we can also add a TimeEdit widget as well.

**Comment by haesleinhuepf** [comment]
> wait a minute ... are you using magicgui 0.1.6?

Yes. I had issues making the transition to 0.2.? and wanted to wait until things stabilize. I'm using these annotitions [a lot](https://github.com/clEsperanto/napari_pyclesperanto_assistant/blob/master/napari_pyclesperanto_assistant/_operations/_operations.py#L13). Min/max is set to 0...99 per default which makes some operations hard to configure. How could one specify e.g. min/max values in upcoming release? Or are the limits gone?

**Comment by tlambert03** [comment]
yeah, sorry, it was a big change.  v0.1.x was a great proof of principle, but I regretted a lot of things and now is the time to change.  Things should start settling down now.  in v0.2.1+ you can set min/max with `{'min': -1000, 'max': 1000}`.  After a little discussion, we chose to [go with the ipywidgets API](https://github.com/napari/magicgui/pull/60) over the Qt API, to stick with the general python datascience vibe.

In general, if you're wondering what [parameter/widget specific options](https://napari.org/magicgui/usage/configuration.html#parameter-specific-options) you can use, you can look at the documentation for the constructor of the corresponding widget type.  For instance, for your `float` values, you'd be able to use any of the options for the [`FloatSpinBox`](https://napari.org/magicgui/_autosummary/magicgui.widgets.FloatSpinBox.html#magicgui.widgets.FloatSpinBox) widget (or, more generally, any of the [`Ranged Widgets`](https://napari.org/magicgui/api/widgets.html#ranged-widgets)).

We can gradually add back things like `displayFormat` for strings, or `validators` and stuff like that, but we'll do so in an explicit magicgui API way, rather than an implicit "pass to Qt" sort of way.
